# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'dgeraldo' -Path (Join-Path (Join-Path $toolsDir 'bin') 'dgeraldo.bat')
Install-BinFile -Name 'geraldo' -Path (Join-Path (Join-Path $toolsDir 'bin') 'geraldo.bat')
